// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IDManager is an autogenerated mock type for the IDManager type
type IDManager struct {
	mock.Mock
}

// Generate provides a mock function with given fields:
func (_m *IDManager) Generate() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewIDManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewIDManager creates a new instance of IDManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIDManager(t mockConstructorTestingTNewIDManager) *IDManager {
	mock := &IDManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
